version: 0.2
phases:
  install:
    commands:
    - npm install
    - npm uninstall react-static
    - npm install --save babel-runtime
    - npm install --save-dev @babel/plugin-transform-runtime
    - npm install --save @babel/runtime
    - git clone https://github.com/briankopp/react-static
    - npm install -g yarn
  pre_build:
    commands:
    - echo installing react static
    - cd react-static
    - yarn
    - yarn build
    - yarn link
    - cd ..
    - yarn link react-static
    - echo finished installing my version of react-static
    - echo copying out post content
    - aws s3 cp s3://codekoppreactstaticcontent . --recursive
    - echo finished copying out post content
  build:
    commands:
    - react-static build
  post_build:
    commands:
artifacts:
  files:
  - dist/**/*
